In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Bird Strikes.csv")

In [4]:
df.head()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,1900,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/01 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/01 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,09-05-2002 00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,6/23/03 0:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No

In [5]:
df.info

<bound method DataFrame.info of        Record ID Aircraft: Type                    Airport: Name Altitude bin  \
0         202152       Airplane                     LAGUARDIA NY    > 1000 ft
1         208159       Airplane      DALLAS/FORT WORTH INTL ARPT    < 1000 ft
2         207601       Airplane                LAKEFRONT AIRPORT    < 1000 ft
3         215953       Airplane              SEATTLE-TACOMA INTL    < 1000 ft
4         219878       Airplane                     NORFOLK INTL    < 1000 ft
...          ...            ...                              ...          ...
25553     321151       Airplane                REDDING MUNICIPAL    > 1000 ft
25554     319677       Airplane                     ORLANDO INTL    < 1000 ft
25555     319680            NaN                              NaN          NaN
25556     319679       Airplane  DETROIT METRO WAYNE COUNTY ARPT    < 1000 ft
25557     319593       Airplane     ABRAHAM LINCOLN CAPITAL ARPT    < 1000 ft

      Aircraft: Make/Model Wildlife: Number struck  \
0                B-737-400                Over 100
1                    MD-80                Over 100
2                    C-500                Over 100
3                B-737-400                Over 100
4             CL-RJ100/200                Over 100
...                    ...                     ...
25553              EMB-120                       1
25554                A-321                       1
25555               EC-135                     NaN
25556            B-757-200                       1
25557            B-737-400                       1

       Wildlife: Number Struck Actual Effect: Impact to flight  \
0                                 859         Engine Shut Down
1                                 424                      NaN
2                                 261                      NaN
3                                 806    Precautionary Landing
4                                 942                      NaN
...                               ...                      ...
25553                               1                      NaN
25554                               1                      NaN
25555                               1                      NaN
25556                               1                      NaN
25557                               1                      NaN

             FlightDate Effect: Indicated Damage  ...  \
0                  1900            Caused damage  ...
1          7/25/01 0:00            Caused damage  ...
2          9/14/01 0:00                No damage  ...
3      09-05-2002 00:00                No damage  ...
4          6/23/03 0:00                No damage  ...
...                 ...                      ...  ...
25553     12/30/11 0:00                No damage  ...
25554     12/30/11 0:00                No damage  ...
25555               NaN                No damage  ...
25556     12/31/11 0:00                No damage  ...
25557     12/31/11 0:00            Caused damage  ...

      Remains of wildlife sent to Smithsonian  \
0                                       False
1                                       False
2                                       False
3                                       False
4                                       False
...                                       ...
25553                                   False
25554                                   False
25555                                   False
25556                                   False
25557                                   False

                                                 Remarks Wildlife: Size  \
0      FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...         Medium
1      102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...          Small
2      FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...          Small
3      NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...          Small
4                                          NO DMG REPTD.          Small
...                                                  ...            ...
25553                                DUCK? NO DMG REPTD.          Large
25554                                                NaN          Small
25555  STRUCK BIRD ON RT FRONT DURING T/O. BIRD REPTD...            NaN
25556  PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...         Medium
25557  HIT CENTER OF RADOME, CAVING IN ABOUT 12". RAD...         Medium

      Conditions: Sky      Wildlife: Species  \
0            No Cloud  Unknown bird - medium
1          Some Cloud            Rock pigeon
2            No Cloud      European starling
3          Some Cloud      European starling
4            No Cloud      European starling
...               ...                    ...
25553        Overcast   Unknown bird - large
25554      Some Cloud           Tree swallow
25555        No Cloud   Unknown bird - small
25556      Some Cloud  Unknown bird - medium
25557        No Cloud        Red-tailed hawk

       Pilot warned of birds or wildlife?  Cost: Total $ Feet above ground  \
0                                       N         30,736             1,500
1                                       Y              0                 0
2                                       N              0                50
3                                       Y              0                50
4                                       N              0                50
...                                   ...            ...               ...
25553                                   N              0             1,500
25554                                   Y              0                 0
25555                                 NaN              0               NaN
25556                                   Y              0                 0
25557                                   N              0                 0

      Number of people injured Is Aircraft Large?
0                            0                Yes
1                            0                 No
2                            0                 No
3                            0                Yes
4                            0                 No
...                        ...                ...
25553                        0                 No
25554                        0                 No
25555                        0                NaN
25556                        0                Yes
25557                        0                Yes

[25558 rows x 26 columns]>

In [6]:
df.columns

Index(['Record ID', 'Aircraft: Type', 'Airport: Name', 'Altitude bin',
       'Aircraft: Make/Model', 'Wildlife: Number struck',
       'Wildlife: Number Struck Actual', 'Effect: Impact to flight',
       'FlightDate', 'Effect: Indicated Damage',
       'Aircraft: Number of engines?', 'Aircraft: Airline/Operator',
       'Origin State', 'When: Phase of flight', 'Conditions: Precipitation',
       'Remains of wildlife collected?',
       'Remains of wildlife sent to Smithsonian', 'Remarks', 'Wildlife: Size',
       'Conditions: Sky', 'Wildlife: Species',
       'Pilot warned of birds or wildlife?', 'Cost: Total $',
       'Feet above ground', 'Number of people injured', 'Is Aircraft Large?'],
      dtype='object')

In [7]:
df.isna().sum()

Record ID                                      0
Aircraft: Type                               129
Airport: Name                                129
Altitude bin                                 129
Aircraft: Make/Model                           0
Wildlife: Number struck                      129
Wildlife: Number Struck Actual                 0
Effect: Impact to flight                   23480
FlightDate                                   129
Effect: Indicated Damage                       0
Aircraft: Number of engines?                 267
Aircraft: Airline/Operator                   129
Origin State                                 449
When: Phase of flight                        129
Conditions: Precipitation                  23543
Remains of wildlife collected?                 0
Remains of wildlife sent to Smithsonian        0
Remarks                                     4771
Wildlife: Size                               129
Conditions: Sky                                0
Wildlife: Species                              0
Pilot warned of birds or wildlife?           129
Cost: Total $                                  0
Feet above ground                            129
Number of people injured                       0
Is Aircraft Large?                           129
dtype: int64

In [8]:
df.isnull().sum()

Record ID                                      0
Aircraft: Type                               129
Airport: Name                                129
Altitude bin                                 129
Aircraft: Make/Model                           0
Wildlife: Number struck                      129
Wildlife: Number Struck Actual                 0
Effect: Impact to flight                   23480
FlightDate                                   129
Effect: Indicated Damage                       0
Aircraft: Number of engines?                 267
Aircraft: Airline/Operator                   129
Origin State                                 449
When: Phase of flight                        129
Conditions: Precipitation                  23543
Remains of wildlife collected?                 0
Remains of wildlife sent to Smithsonian        0
Remarks                                     4771
Wildlife: Size                               129
Conditions: Sky                                0
Wildlife: Species                              0
Pilot warned of birds or wildlife?           129
Cost: Total $                                  0
Feet above ground                            129
Number of people injured                       0
Is Aircraft Large?                           129
dtype: int64

In [9]:
df.ndim

2

In [10]:
df.shape

(25558, 26)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Record ID                                25558 non-null  int64
 1   Aircraft: Type                           25429 non-null  object
 2   Airport: Name                            25429 non-null  object
 3   Altitude bin                             25429 non-null  object
 4   Aircraft: Make/Model                     25558 non-null  object
 5   Wildlife: Number struck                  25429 non-null  object
 6   Wildlife: Number Struck Actual           25558 non-null  int64
 7   Effect: Impact to flight                 2078 non-null   object
 8   FlightDate                               25429 non-null  object
 9   Effect: Indicated Damage                 25558 non-null  object
 10  Aircraft: Number of engines?             25291 non-null  object
 11  Aircraft: Airline/Operator               25429 non-null  object
 12  Origin State                             25109 non-null  object
 13  When: Phase of flight                    25429 non-null  object
 14  Conditions: Precipitation                2015 non-null   object
 15  Remains of wildlife collected?           25558 non-null  bool
 16  Remains of wildlife sent to Smithsonian  25558 non-null  bool
 17  Remarks                                  20787 non-null  object
 18  Wildlife: Size                           25429 non-null  object
 19  Conditions: Sky                          25558 non-null  object
 20  Wildlife: Species                        25558 non-null  object
 21  Pilot warned of birds or wildlife?       25429 non-null  object
 22  Cost: Total $                            25558 non-null  object
 23  Feet above ground                        25429 non-null  object
 24  Number of people injured                 25558 non-null  int64
 25  Is Aircraft Large?                       25429 non-null  object
dtypes: bool(2), int64(3), object(21)
memory usage: 4.7+ MB

In [12]:
df1=df.copy()

In [13]:
df1.head()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,1900,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/01 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/01 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,09-05-2002 00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,6/23/03 0:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No

In [14]:
df1.dropna(subset=['Aircraft: Type','Airport: Name', 'Altitude bin','Wildlife: Number struck','FlightDate','Aircraft: Number of engines?','Aircraft: Airline/Operator','Origin State','When: Phase of flight','Wildlife: Size','Pilot warned of birds or wildlife?','Feet above ground','Is Aircraft Large?'],inplace=True)

In [15]:
df1

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,1900,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/01 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/01 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,09-05-2002 00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,6/23/03 0:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,319672,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,NaN,12/29/11 0:00,No damage,...,True,ID BY SMITHSONIAN. SAMPLES FROM BOTH A/C AND B...,Medium,No Cloud,Mallard,Y,0,10,0,Yes
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,12/30/11 0:00,No damage,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,"1,500",0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,12/30/11 0:00,No damage,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,12/31/11 0:00,No damage,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,12/31/11 0:00,Caused damage,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [16]:
df1.isnull().sum()

Record ID                                      0
Aircraft: Type                                 0
Airport: Name                                  0
Altitude bin                                   0
Aircraft: Make/Model                           0
Wildlife: Number struck                        0
Wildlife: Number Struck Actual                 0
Effect: Impact to flight                   22752
FlightDate                                     0
Effect: Indicated Damage                       0
Aircraft: Number of engines?                   0
Aircraft: Airline/Operator                     0
Origin State                                   0
When: Phase of flight                          0
Conditions: Precipitation                  22771
Remains of wildlife collected?                 0
Remains of wildlife sent to Smithsonian        0
Remarks                                     4605
Wildlife: Size                                 0
Conditions: Sky                                0
Wildlife: Species                              0
Pilot warned of birds or wildlife?             0
Cost: Total $                                  0
Feet above ground                              0
Number of people injured                       0
Is Aircraft Large?                             0
dtype: int64

In [17]:
df1.to_csv(r'C:\Users\Divyanshu\Desktop\Intenship(UNi)\Bird_Strike\Bird_clean.csv',index = False)

In [18]:
d = list

In [19]:
df1.drop(index = 0,inplace = True)

In [20]:
date_strings= df1['FlightDate'].tolist()

In [21]:
from datetime import datetime
def extract_year(date_string):
    if '/' in date_string:
        # If date string uses '/', use a different format
        date_object = datetime.strptime(date_string, '%m/%d/%y %H:%M')
    else:
        # If date string uses '-', use another format
        date_object = datetime.strptime(date_string, '%m-%d-%Y %H:%M')
    return date_object.year

# Extracting years from each date string
years = [extract_year(date_str) for date_str in date_strings]

In [22]:
df1

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,7/25/01 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,9/14/01 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,09-05-2002 00:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,6/23/03 0:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No
6,221697,Airplane,NEW CASTLE COUNTY,< 1000 ft,LEARJET-25,Over 100,227,Other,8/17/03 0:00,Caused damage,...,True,NaN,Small,No Cloud,European starling,N,"14,81,711",150,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,319672,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,NaN,12/29/11 0:00,No damage,...,True,ID BY SMITHSONIAN. SAMPLES FROM BOTH A/C AND B...,Medium,No Cloud,Mallard,Y,0,10,0,Yes
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,12/30/11 0:00,No damage,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,"1,500",0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,12/30/11 0:00,No damage,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,12/31/11 0:00,No damage,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,12/31/11 0:00,Caused damage,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [23]:
df1.drop(['FlightDate'],axis =1,inplace = True)

In [24]:
df1

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,Caused damage,2,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,No damage,2,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,No damage,2,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,No damage,2,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No
6,221697,Airplane,NEW CASTLE COUNTY,< 1000 ft,LEARJET-25,Over 100,227,Other,Caused damage,2,...,True,NaN,Small,No Cloud,European starling,N,"14,81,711",150,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,319672,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,NaN,No damage,2,...,True,ID BY SMITHSONIAN. SAMPLES FROM BOTH A/C AND B...,Medium,No Cloud,Mallard,Y,0,10,0,Yes
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,No damage,2,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,"1,500",0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,No damage,2,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,No damage,2,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,Caused damage,2,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [25]:
df1["flightDate"] = years

In [26]:
df1

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,Effect: Indicated Damage,Aircraft: Number of engines?,...,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?,flightDate
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,NaN,Caused damage,2,...,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No,2001
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,NaN,No damage,2,...,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No,2001
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,No damage,2,...,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes,2002
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,NaN,No damage,2,...,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No,2003
6,221697,Airplane,NEW CASTLE COUNTY,< 1000 ft,LEARJET-25,Over 100,227,Other,Caused damage,2,...,NaN,Small,No Cloud,European starling,N,"14,81,711",150,0,No,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,319672,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,NaN,No damage,2,...,ID BY SMITHSONIAN. SAMPLES FROM BOTH A/C AND B...,Medium,No Cloud,Mallard,Y,0,10,0,Yes,2011
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,NaN,No damage,2,...,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,"1,500",0,No,2011
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,NaN,No damage,2,...,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No,2011
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,NaN,No damage,2,...,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes,2011
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,NaN,Caused damage,2,...,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes,2011

In [28]:
df1.to_csv(r'C:\Users\Divyanshu\Desktop\Intenship(UNi)\Bird_Strike\Bird_clean2.csv',index = False)